version: '3.8'

services:
  db_user_service:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  db_post_service:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"

  user_service:
    build: ./user_service
    command: gunicorn user_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./user_service:/connectify/user_service
    depends_on:
      - db_user_service
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_user_service:5432/${POSTGRES_DB}
    ports:
      - "8001:8000"

  post_service:
    build: ./post_service
    command: gunicorn post_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./post_service:/connectify/post_service
    depends_on:
      - db_post_service
      - rabbitmq
      - elasticsearch
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_post_service:5432/${POSTGRES_DB}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "8002:8000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user_service
      - post_service

volumes:
  esdata:
